---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-machine-learning/resources/bANLa) course resource._

---

# Assignment 2

In this assignment you'll explore the relationship between model complexity and generalization performance, by adjusting key parameters of various supervised learning models. Part 1 of this assignment will look at regression and Part 2 will look at classification.

## Part 1 - Regression

First, run the following block to set up the variables needed for later sections.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


np.random.seed(0)
n = 15
x = np.linspace(0,10,n) + np.random.randn(n)/5
y = np.sin(x)+x/6 + np.random.randn(n)/10


X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=0)

# You can use this function to help you visualize the dataset by
# plotting a scatterplot of the data points
# in the training and test sets.
def part1_scatter():
    %matplotlib notebook
    plt.figure()
    plt.scatter(X_train, y_train, label='training data')
    plt.scatter(X_test, y_test, label='test data')
    plt.legend(loc=4);
    
    
# NOTE: Uncomment the function below to visualize the data, but be sure 
# to **re-comment it before submitting this assignment to the autograder**.   
#part1_scatter()

### Question 1

Write a function that fits a polynomial LinearRegression model on the *training data* `X_train` for degrees 1, 3, 6, and 9. (Use PolynomialFeatures in sklearn.preprocessing to create the polynomial features and then fit a linear regression model) For each model, find 100 predicted values over the interval x = 0 to 10 (e.g. `np.linspace(0,10,100)`) and store this in a numpy array. The first row of this array should correspond to the output from the model trained on degree 1, the second row degree 3, the third row degree 6, and the fourth row degree 9.

<img src="readonly/polynomialreg1.png" style="width: 1000px;"/>

The figure above shows the fitted models plotted on top of the original data (using `plot_one()`).

<br>
*This function should return a numpy array with shape `(4, 100)`*

In [2]:
print('X_train: ', X_train)
print('y_train: ', y_train)
print('X_test: ', X_test)
print('y_test: ', y_test)

X_train:  [ 10.08877265   3.23065446   1.62431903   9.31004929   7.17166586
   4.96972856   8.14799756   2.59103578   0.35281047   3.375973
   8.72363612]
y_train:  [ 1.21213026  0.36408873  1.24877201  1.81942995  1.82595557 -0.05233879
  2.31966323  0.98630796  0.43770571  0.07512287  2.08031157]
X_test:  [ 0.79431716  4.47573197  5.69364194  6.51069113]
y_test:  [ 0.99517935 -0.16081     0.3187423   1.53763897]


In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [4]:
x.shape

(15,)

In [5]:
x = x.reshape(len(x), 1)
print(x.shape)
x

(15, 1)


array([[  0.35281047],
       [  0.79431716],
       [  1.62431903],
       [  2.59103578],
       [  3.23065446],
       [  3.375973  ],
       [  4.47573197],
       [  4.96972856],
       [  5.69364194],
       [  6.51069113],
       [  7.17166586],
       [  8.14799756],
       [  8.72363612],
       [  9.31004929],
       [ 10.08877265]])

In [6]:
x_pred = np.linspace(0,10,100)
len(x_pred)

100

In [7]:
x_pred

array([  0.        ,   0.1010101 ,   0.2020202 ,   0.3030303 ,
         0.4040404 ,   0.50505051,   0.60606061,   0.70707071,
         0.80808081,   0.90909091,   1.01010101,   1.11111111,
         1.21212121,   1.31313131,   1.41414141,   1.51515152,
         1.61616162,   1.71717172,   1.81818182,   1.91919192,
         2.02020202,   2.12121212,   2.22222222,   2.32323232,
         2.42424242,   2.52525253,   2.62626263,   2.72727273,
         2.82828283,   2.92929293,   3.03030303,   3.13131313,
         3.23232323,   3.33333333,   3.43434343,   3.53535354,
         3.63636364,   3.73737374,   3.83838384,   3.93939394,
         4.04040404,   4.14141414,   4.24242424,   4.34343434,
         4.44444444,   4.54545455,   4.64646465,   4.74747475,
         4.84848485,   4.94949495,   5.05050505,   5.15151515,
         5.25252525,   5.35353535,   5.45454545,   5.55555556,
         5.65656566,   5.75757576,   5.85858586,   5.95959596,
         6.06060606,   6.16161616,   6.26262626,   6.36

In [8]:
print(x_pred.shape)

(100,)


In [9]:
x_pred = x_pred.reshape(len(x_pred), 1)

In [10]:
poly_1 = PolynomialFeatures(degree=1)
X_poly_1 = poly_1.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X_poly_1, y,
                                                   random_state = 0)
linreg_1 = LinearRegression().fit(X_train, y_train)

In [11]:
x_pred_poly_1 = poly_1.fit_transform(x_pred)
y1 = linreg_1.predict(x_pred_poly_1)

In [12]:
poly_3 = PolynomialFeatures(degree=3)
X_poly_3 = poly_3.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X_poly_3, y,
                                                   random_state = 0)
linreg_3 = LinearRegression().fit(X_train, y_train)
x_pred_poly_3 = poly_3.fit_transform(x_pred)
y3 = linreg_3.predict(x_pred_poly_3)

In [13]:
poly_6 = PolynomialFeatures(degree=6)
X_poly_6 = poly_6.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X_poly_6, y,
                                                   random_state = 0)
linreg_6 = LinearRegression().fit(X_train, y_train)
x_pred_poly_6 = poly_6.fit_transform(x_pred)
y6 = linreg_6.predict(x_pred_poly_6)

In [14]:
poly_9 = PolynomialFeatures(degree=9)
X_poly_9 = poly_9.fit_transform(x)
X_train, X_test, y_train, y_test = train_test_split(X_poly_9, y,
                                                   random_state = 0)
linreg_9 = LinearRegression().fit(X_train, y_train)
x_pred_poly_9 = poly_9.fit_transform(x_pred)
y9 = linreg_9.predict(x_pred_poly_9)

In [15]:
type(y1)

numpy.ndarray

In [16]:
y1.shape

(100,)

In [17]:
y1 = y1.reshape(len(y1), 1)
y3 = y3.reshape(len(y3), 1)
y6 = y6.reshape(len(y6), 1)
y9 = y9.reshape(len(y9), 1)

In [18]:
y1.shape

(100, 1)

In [19]:
y1 = np.transpose(y1)
y3 = np.transpose(y3)
y6 = np.transpose(y6)
y9 = np.transpose(y9)

In [20]:
print(y1.shape)
print(y3.shape)
print(y6.shape)
print(y9.shape)

(1, 100)
(1, 100)
(1, 100)
(1, 100)


In [21]:
ans_one = np.concatenate((y1, y3, y6, y9), axis=0)

In [22]:
ans_one.shape

(4, 100)

In [23]:
def answer_one():
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures

    # Your code here
    
    x = x.reshape(len(x), 1)
    x_pred = np.linspace(0,10,100)
    x_pred = x_pred.reshape(len(x_pred), 1)
    
    # Poly degree 1
    poly_1 = PolynomialFeatures(degree=1)
    X_poly_1 = poly_1.fit_transform(x)
    X_train, X_test, y_train, y_test = train_test_split(X_poly_1, y, random_state = 0)
    linreg_1 = LinearRegression().fit(X_train, y_train)
    x_pred_poly_1 = poly_1.fit_transform(x_pred)
    y1 = linreg_1.predict(x_pred_poly_1)
    
    # Poly degree 3
    poly_3 = PolynomialFeatures(degree=3)
    X_poly_3 = poly_3.fit_transform(x)
    X_train, X_test, y_train, y_test = train_test_split(X_poly_3, y, random_state = 0)
    linreg_3 = LinearRegression().fit(X_train, y_train)
    x_pred_poly_3 = poly_3.fit_transform(x_pred)
    y3 = linreg_3.predict(x_pred_poly_3)
    
    # Poly degree 6    
    poly_6 = PolynomialFeatures(degree=6)
    X_poly_6 = poly_6.fit_transform(x)
    X_train, X_test, y_train, y_test = train_test_split(X_poly_6, y, random_state = 0)
    linreg_6 = LinearRegression().fit(X_train, y_train)
    x_pred_poly_6 = poly_6.fit_transform(x_pred)
    y6 = linreg_6.predict(x_pred_poly_6)
    
    # Poly degree 9        
    poly_9 = PolynomialFeatures(degree=9)
    X_poly_9 = poly_9.fit_transform(x)
    X_train, X_test, y_train, y_test = train_test_split(X_poly_9, y, random_state = 0)
    linreg_9 = LinearRegression().fit(X_train, y_train)
    x_pred_poly_9 = poly_9.fit_transform(x_pred)
    y9 = linreg_9.predict(x_pred_poly_9)
    
    y1 = y1.reshape(len(y1), 1)
    y3 = y3.reshape(len(y3), 1)
    y6 = y6.reshape(len(y6), 1)
    y9 = y9.reshape(len(y9), 1)
    y1 = np.transpose(y1)
    y3 = np.transpose(y3)
    y6 = np.transpose(y6)
    y9 = np.transpose(y9)
    ans_one = np.concatenate((y1, y3, y6, y9), axis=0)
    
    return ans_one

In [24]:
ans_one.shape

(4, 100)

In [25]:
# feel free to use the function plot_one() to replicate the figure 
# from the prompt once you have completed question one
def plot_one(degree_predictions):
    plt.figure(figsize=(10,5))
    plt.plot(X_train, y_train, 'o', label='training data', markersize=10)
    plt.plot(X_test, y_test, 'o', label='test data', markersize=10)
    for i,degree in enumerate([1,3,6,9]):
        plt.plot(np.linspace(0,10,100), degree_predictions[i], alpha=0.8, lw=2, label='degree={}'.format(degree))
    plt.ylim(-1,2.5)
    plt.legend(loc=4)

#plot_one(answer_one())

### Question 2

Write a function that fits a polynomial LinearRegression model on the training data `X_train` for degrees 0 through 9. For each model compute the $R^2$ (coefficient of determination) regression score on the training data as well as the the test data, and return both of these arrays in a tuple.

*This function should return one tuple of numpy arrays `(r2_train, r2_test)`. Both arrays should have shape `(10,)`*

In [26]:
def answer_two():
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.metrics.regression import r2_score

    # Your code here
    L = list(range(10))
    arr_R2_train = np.ones((10,))
    arr_R2_test = np.ones((10,))

    for i in L:
        poly = PolynomialFeatures(degree=L[i])
        X_poly = poly.fit_transform(x)
        X_train, X_test, y_train, y_test = train_test_split(X_poly, y, random_state = 0)
        linreg  = LinearRegression().fit(X_train, y_train)
        y_train_pred = linreg.predict(X_train)
        R2_train = r2_score(y_train, y_train_pred)
        y_test_pred = linreg.predict(X_test)
        R2_test = r2_score(y_test, y_test_pred)
        arr_R2_train[L[i]] = R2_train
        arr_R2_test[L[i]] = R2_test

    arr = np.array((arr_R2_train,arr_R2_test))
    
    return tuple(map(tuple, arr))

In [27]:
answer_two()

((0.0,
  0.42924577812346632,
  0.45109980444082465,
  0.58719953687798476,
  0.91941944717693158,
  0.97578641430681867,
  0.99018233247950893,
  0.99352509278402767,
  0.99637545387745396,
  0.99803706256582003),
 (-0.47808641737141788,
  -0.45237104233936676,
  -0.068569841499158901,
  0.0053310529457279987,
  0.73004942818715057,
  0.87708300916504855,
  0.92140939812771439,
  0.92021504118071584,
  0.63247943762578407,
  -0.64525446868451852))

### Question 3

Based on the $R^2$ scores from question 2 (degree levels 0 through 9), what degree level corresponds to a model that is underfitting? What degree level corresponds to a model that is overfitting? What choice of degree level would provide a model with good generalization performance on this dataset? Note: there may be multiple correct solutions to this question.

(Hint: Try plotting the $R^2$ scores from question 2 to visualize the relationship between degree level and $R^2$)

*This function should return one tuple with the degree values in this order: `(Underfitting, Overfitting, Good_Generalization)`*

In [30]:
R2 = answer_two()
R2_train = R2[0]
R2_test = R2[1]

In [41]:
#import matplotlib.pyplot as plt

In [42]:
#plt.figure()
#plt.plot(R2_train, '-o', R2_test, '-o')
#plt.legend(['R2_train', 'R2_test'])
#plt.show()

In [43]:
def answer_three():
    
    # Your code here
    
    return (0, 9, 7)

In [44]:
type(answer_three())

tuple

### Question 4

Training models on high degree polynomial features can result in overly complex models that overfit, so we often use regularized versions of the model to constrain model complexity, as we saw with Ridge and Lasso linear regression.

For this question, train two models: a non-regularized LinearRegression model (default parameters) and a regularized Lasso Regression model (with parameters `alpha=0.01`, `max_iter=10000`) on polynomial features of degree 12. Return the $R^2$ score for both the LinearRegression and Lasso model's test sets.

*This function should return one tuple `(LinearRegression_R2_test_score, Lasso_R2_test_score)`*

In [ ]:
linreg = LinearRegression().fit(X_train, y_train)

In [ ]:
def answer_four():
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.linear_model import Lasso, LinearRegression
    from sklearn.metrics.regression import r2_score

    # Your code here

    return # Your answer here

## Part 2 - Classification

Here's an application of machine learning that could save your life! For this section of the assignment we will be working with the [UCI Mushroom Data Set](http://archive.ics.uci.edu/ml/datasets/Mushroom?ref=datanews.io) stored in `mushrooms.csv`. The data will be used to train a model to predict whether or not a mushroom is poisonous. The following attributes are provided:

*Attribute Information:*

1. cap-shape: bell=b, conical=c, convex=x, flat=f, knobbed=k, sunken=s 
2. cap-surface: fibrous=f, grooves=g, scaly=y, smooth=s 
3. cap-color: brown=n, buff=b, cinnamon=c, gray=g, green=r, pink=p, purple=u, red=e, white=w, yellow=y 
4. bruises?: bruises=t, no=f 
5. odor: almond=a, anise=l, creosote=c, fishy=y, foul=f, musty=m, none=n, pungent=p, spicy=s 
6. gill-attachment: attached=a, descending=d, free=f, notched=n 
7. gill-spacing: close=c, crowded=w, distant=d 
8. gill-size: broad=b, narrow=n 
9. gill-color: black=k, brown=n, buff=b, chocolate=h, gray=g, green=r, orange=o, pink=p, purple=u, red=e, white=w, yellow=y 
10. stalk-shape: enlarging=e, tapering=t 
11. stalk-root: bulbous=b, club=c, cup=u, equal=e, rhizomorphs=z, rooted=r, missing=? 
12. stalk-surface-above-ring: fibrous=f, scaly=y, silky=k, smooth=s 
13. stalk-surface-below-ring: fibrous=f, scaly=y, silky=k, smooth=s 
14. stalk-color-above-ring: brown=n, buff=b, cinnamon=c, gray=g, orange=o, pink=p, red=e, white=w, yellow=y 
15. stalk-color-below-ring: brown=n, buff=b, cinnamon=c, gray=g, orange=o, pink=p, red=e, white=w, yellow=y 
16. veil-type: partial=p, universal=u 
17. veil-color: brown=n, orange=o, white=w, yellow=y 
18. ring-number: none=n, one=o, two=t 
19. ring-type: cobwebby=c, evanescent=e, flaring=f, large=l, none=n, pendant=p, sheathing=s, zone=z 
20. spore-print-color: black=k, brown=n, buff=b, chocolate=h, green=r, orange=o, purple=u, white=w, yellow=y 
21. population: abundant=a, clustered=c, numerous=n, scattered=s, several=v, solitary=y 
22. habitat: grasses=g, leaves=l, meadows=m, paths=p, urban=u, waste=w, woods=d

<br>

The data in the mushrooms dataset is currently encoded with strings. These values will need to be encoded to numeric to work with sklearn. We'll use pd.get_dummies to convert the categorical variables into indicator variables. 

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


mush_df = pd.read_csv('mushrooms.csv')
mush_df2 = pd.get_dummies(mush_df)

X_mush = mush_df2.iloc[:,2:]
y_mush = mush_df2.iloc[:,1]

# use the variables X_train2, y_train2 for Question 5
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_mush, y_mush, random_state=0)

# For performance reasons in Questions 6 and 7, we will create a smaller version of the
# entire mushroom dataset for use in those questions.  For simplicity we'll just re-use
# the 25% test split created above as the representative subset.
#
# Use the variables X_subset, y_subset for Questions 6 and 7.
X_subset = X_test2
y_subset = y_test2

### Question 5

Using `X_train2` and `y_train2` from the preceeding cell, train a DecisionTreeClassifier with default parameters and random_state=0. What are the 5 most important features found by the decision tree?

As a reminder, the feature names are available in the `X_train2.columns` property, and the order of the features in `X_train2.columns` matches the order of the feature importance values in the classifier's `feature_importances_` property. 

*This function should return a list of length 5 containing the feature names in descending order of importance.*


In [ ]:
def answer_five():
    from sklearn.tree import DecisionTreeClassifier

    # Your code here

    return # Your answer here

### Question 6

For this question, we're going to use the `validation_curve` function in `sklearn.model_selection` to determine training and test scores for a Support Vector Classifier (`SVC`) with varying parameter values.  Recall that the validation_curve function, in addition to taking an initialized unfitted classifier object, takes a dataset as input and does its own internal train-test splits to compute results.

**Because creating a validation curve requires fitting multiple models, for performance reasons this question will use just a subset of the original mushroom dataset: please use the variables X_subset and y_subset as input to the validation curve function (instead of X_mush and y_mush) to reduce computation time.**

The initialized unfitted classifier object we'll be using is a Support Vector Classifier with radial basis kernel.  So your first step is to create an `SVC` object with default parameters (i.e. `kernel='rbf', C=1`) and `random_state=0`. Recall that the kernel width of the RBF kernel is controlled using the `gamma` parameter.  

With this classifier, and the dataset in X_subset, y_subset, explore the effect of `gamma` on classifier accuracy by using the `validation_curve` function to find the training and test scores for 6 values of `gamma` from `0.0001` to `10` (i.e. `np.logspace(-4,1,6)`). Recall that you can specify what scoring metric you want validation_curve to use by setting the "scoring" parameter.  In this case, we want to use "accuracy" as the scoring metric.

For each level of `gamma`, `validation_curve` will fit 3 models on different subsets of the data, returning two 6x3 (6 levels of gamma x 3 fits per level) arrays of the scores for the training and test sets.

Find the mean score across the three models for each level of `gamma` for both arrays, creating two arrays of length 6, and return a tuple with the two arrays.

e.g.

if one of your array of scores is

    array([[ 0.5,  0.4,  0.6],
           [ 0.7,  0.8,  0.7],
           [ 0.9,  0.8,  0.8],
           [ 0.8,  0.7,  0.8],
           [ 0.7,  0.6,  0.6],
           [ 0.4,  0.6,  0.5]])
       
it should then become

    array([ 0.5,  0.73333333,  0.83333333,  0.76666667,  0.63333333, 0.5])

*This function should return one tuple of numpy arrays `(training_scores, test_scores)` where each array in the tuple has shape `(6,)`.*

In [ ]:
def answer_six():
    from sklearn.svm import SVC
    from sklearn.model_selection import validation_curve

    # Your code here

    return # Your answer here

### Question 7

Based on the scores from question 6, what gamma value corresponds to a model that is underfitting (and has the worst test set accuracy)? What gamma value corresponds to a model that is overfitting (and has the worst test set accuracy)? What choice of gamma would be the best choice for a model with good generalization performance on this dataset (high accuracy on both training and test set)? Note: there may be multiple correct solutions to this question.

(Hint: Try plotting the scores from question 6 to visualize the relationship between gamma and accuracy.)

*This function should return one tuple with the degree values in this order: `(Underfitting, Overfitting, Good_Generalization)`*

In [ ]:
def answer_seven():
    
    # Your code here
    
    return # Return your answer